# This workflow will ensures that a set of different feature configuration builds on linux

name: Build Feature Configurations

on:
  pull_request:
    branches: [main]
    paths:
      - '*/**'
      - '!docs/**'

env:
  go_version: "1.21.x"

jobs:
  cmake_script:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Simple Conf CMake script", short: "simple", features: "api,core,stubs,examples" }
          - { name: "Monitor Conf CMake script", short: "monitor", features: "api,core,stubs,monitor,examples" }
          - { name: "OLink Conf CMake script", short: "olink", features: "api,core,stubs,olink,examples_olink" }
          - { name: "MQTT Conf CMake script", short: "mqtt", features: "api,core,stubs,mqtt,examples_mqtt" }
          - { name: "Nats Conf CMake script", short: "nats", features: "api,core,stubs,nats,examples_nats" }
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-go@v5
        with:
          go-version: ${{env.go_version}}

      - uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ env.go_version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ env.go_version }}-

      - run: cmake --version

      - name: Install catch2
        run: git clone --branch v2.13.8 --depth 1 https://github.com/catchorg/Catch2.git && cd Catch2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install

      - name: Install trompeloeil
        if: ${{ matrix.config.short == 'olink'}}
        run: git clone --branch v46 --depth 1 https://github.com/rollbear/trompeloeil.git && cd trompeloeil && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install

      - name: Install nlohmann using apt-get
        run: sudo apt-get install -y nlohmann-json3-dev

      - name: Install eigen3 using apt-get
        run: sudo apt-get install -y libeigen3-dev

      - name: Install poco using apt-get
        if: ${{ matrix.config.short == 'monitor' || matrix.config.short == 'olink' }}
        run: sudo apt-get install -y libpoco-dev

      - name: Install objectlink-core-cpp
        if: ${{ matrix.config.short == 'olink'}}
        run: git clone --branch v0.2.9 --depth 1 https://github.com/apigear-io/objectlink-core-cpp.git && cd objectlink-core-cpp && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install

      - name: Install paho.mqtt.c
        if: ${{ matrix.config.short == 'mqtt'}}
        run: git clone --branch v1.3.13 --depth 1 https://github.com/eclipse/paho.mqtt.c.git && cd paho.mqtt.c && cmake -Bbuild -H. -DPAHO_BUILD_SHARED=OFF -DPAHO_BUILD_STATIC=ON -DPAHO_WITH_SSL=ON -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install

      - name: Install cnats
        if: ${{ matrix.config.short == 'nats'}}
        run: git clone --branch v3.9.1 --depth 1 https://github.com/nats-io/nats.c.git && cd nats.c && cmake -Bbuild -S . -DNATS_BUILD_LIB_SHARED=OFF -DNATS_BUILD_STREAMING=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DNATS_BUILD_STREAMING=OFF -DNATS_BUILD_WITH_TLS=OFF -DNATS_BUILD_STATIC_EXAMPLES=ON -DNATS_BUILD_EXAMPLES=OFF -DCMAKE_C_FLAGS="-include stddef.h" && sudo cmake --build build/ --target install

      - run: go run main.go install
      - name: generate ${{ matrix.config.short }} feature set
        run: bin/apigear g x -f "${{ matrix.config.features }}" -t . -o test -i apigear/test-apis/testbed.simple.module.yaml,apigear/test-apis/testbed.struct.module.yaml

      - name: Create Nats Server for ubuntu (only for nats)
        if: ${{ matrix.config.short == 'nats'}}
        uses: onichandame/nats-action@master
        with:
          port: "4222" 
      - name: Run cmake on Linux
        working-directory: test
        env:
            CTEST_OUTPUT_ON_FAILURE: 1
        run: bash scripts/test_cmake.sh

  cmake_list:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Simple Conf CMake Lists file", short: "simple", features: "api,core,stubs,examples" }
          - { name: "Monitor Conf CMake Lists file", short: "monitor", features: "api,core,stubs,monitor,examples" }
          - { name: "OLink Conf CMake Lists file", short: "olink", features: "api,core,stubs,olink,examples_olink" }
          - { name: "MQTT Conf CMake Lists file", short: "mqtt", features: "api,core,stubs,mqtt,examples_mqtt" }
          - { name: "Nats Conf CMake Lists file", short: "nats", features: "api,core,stubs,nats,examples_nats" }
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-go@v5
        with:
          go-version: ${{env.go_version}}

      - uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ env.go_version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ env.go_version }}-

      - run: cmake --version

      - name: Install catch2
        run: git clone --branch v2.13.8 --depth 1 https://github.com/catchorg/Catch2.git && cd Catch2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install

      - name: Install trompeloeil
        if: ${{ matrix.config.short == 'olink'}}
        run: git clone --branch v46 --depth 1 https://github.com/rollbear/trompeloeil.git && cd trompeloeil && cmake -Bbuild -H. -DPAHO_BUILD_SHARED=OFF -DPAHO_BUILD_STATIC=ON -DPAHO_WITH_SSL=ON -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install

      - name: Install nlohmann using apt-get
        run: sudo apt-get install -y nlohmann-json3-dev

      - name: Install eigen3 using apt-get
        run: sudo apt-get install -y libeigen3-dev

      - name: Install poco using apt-get
        if: ${{ matrix.config.short == 'monitor' || matrix.config.short == 'olink' }}
        run: sudo apt-get install -y libpoco-dev

      - name: Install objectlink-core-cpp
        if: ${{ matrix.config.short == 'olink'}}
        run: git clone --branch v0.2.9 --depth 1 https://github.com/apigear-io/objectlink-core-cpp.git && cd objectlink-core-cpp && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install

      - name: Install paho.mqtt.c
        if: ${{ matrix.config.short == 'mqtt'}}
        run: git clone --branch v1.3.13 --depth 1 https://github.com/eclipse/paho.mqtt.c.git && cd paho.mqtt.c && cmake -Bbuild -H. -DPAHO_BUILD_SHARED=OFF -DPAHO_BUILD_STATIC=ON -DPAHO_WITH_SSL=ON -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install

      - name: Install cnats
        if: ${{ matrix.config.short == 'nats'}}
        run: git clone --branch v3.9.1 --depth 1 https://github.com/nats-io/nats.c.git && cd nats.c && cmake -Bbuild -S . -DNATS_BUILD_LIB_SHARED=OFF -DNATS_BUILD_STREAMING=OFF -DNATS_BUILD_STREAMING=OFF -DNATS_BUILD_WITH_TLS=OFF -DNATS_BUILD_STATIC_EXAMPLES=ON  -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DNATS_BUILD_EXAMPLES=OFF -DCMAKE_C_FLAGS="-include stddef.h" && sudo cmake --build build/ --target install

      - run: go run main.go install
      - name: generate ${{ matrix.config.short }} feature set
        run: bin/apigear g x -f "${{ matrix.config.features }}" -t . -o test -i apigear/test-apis/testbed.simple.module.yaml,apigear/test-apis/testbed.struct.module.yaml

      - name: Create Nats Server for ubuntu (only for nats)
        if: ${{ matrix.config.short == 'nats'}}
        uses: onichandame/nats-action@master
        with:
          port: "4222" 
      - name: Run cmake on Linux
        working-directory: test
        env:
            CTEST_OUTPUT_ON_FAILURE: 1
        run: cmake -DCMAKE_BUILD_TYPE=Release -Bbuild -DCMAKE_INSTALL_PREFIX=tmp -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/deps -DBUILD_TESTING=ON && cmake --build build/ && cmake --build build/ --target test && cmake --build build/ --target install

  conan_build:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Simple Conf Conan", short: "simple", features: "api,core,stubs,examples,conan" }
          - { name: "Monitor Conf Conan", short: "monitor", features: "api,core,stubs,monitor,examples,conan" }
          - { name: "OLink Conf Conan", short: "olink", features: "api,core,stubs,olink,examples_olink,conan" }
          - { name: "MQTT Conf Conan", short: "mqtt", features: "api,core,stubs,mqtt,examples_mqtt,conan" }
          - { name: "Nats Conf Conan", short: "nats", features: "api,core,stubs,nats,examples_nats,conan" }
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-go@v5
        with:
          go-version: ${{env.go_version}}

      - uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ env.go_version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ env.go_version }}-

      - name: Cache conan on Linux
        uses: actions/cache@v4
        with:
          path: |
            ~/.conan2/p
          key: ubuntu-latest-conan-cache-${{ hashFiles('goldenmaster/**/conanfile.py', 'goldenmaster/**/conanfile.txt') }}
          restore-keys: |
            ubuntu-latest-conan-cache
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: "pip"
          cache-dependency-path: ".github/workflows/conan-requirements.txt"
      - name: Install Conan
        run: pip install -r .github/workflows/conan-requirements.txt
      - name: Create default profile
        run: conan profile detect

      - run: cmake --version
      - run: go run main.go install
      - name: generate ${{ matrix.config.short }} feature set
        run: bin/apigear g x -f "${{ matrix.config.features }}" -t . -o test -i apigear/test-apis/testbed.simple.module.yaml
      - name: Create Nats Server for ubuntu (only for nats)
        if: ${{ matrix.config.short == 'nats'}}
        uses: onichandame/nats-action@master
        with:
          port: "4222" 
      - name: Run conan build Linux
        working-directory: test
        env:
            CTEST_OUTPUT_ON_FAILURE: 1
        run: chmod +x ./scripts/test_conan.sh && ./scripts/test_conan.sh
      - name: Archive workspace artifacts for debugging
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.config.short }}-workspace
          path: |
            *
            ~/.conan2/p
          retention-days: 1
